#pragma once
#include <string>
#include <unordered_map>
#include <vector>
#include "/home/professor/mystuffs/MyCompiler/include/Bytecode.h"

// The Virtual Machine (VM) executes the bytecode generated by the Compiler.
// It uses a stack for operations and a map to store variable values.
class VM{
    public:
      // Executes the given chunk of bytecode from start to finish.
      void run(const Chunk& chunk);

    private:
      // Stack for holding intermediate values during execution.
      std::vector<double>stack_;
      // Map to store variable names and their corresponding values.
      std::unordered_map<std::string,double>variables_;

      // Pushes a value onto the stack.
      void push(double value);
      // Pops a value from the stack and returns it.
      // Assumes the stack is not empty (caller must ensure).
      double pop();
};